# Generated by Django 5.1.7 on 2025-03-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language', models.CharField(max_length=50)),
                ('cover', models.CharField(choices=[('s', 'Solid'), ('f', 'Flexible')], default='f', max_length=1)),
                ('publish_time', models.IntegerField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('aupdated_time', models.DateTimeField(auto_now=True)),
                ('isbn', models.CharField(max_length=13, null=True)),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
